Repository techqueria/website, pull requests merged in 2018-10, with the labels that each got.

#79 Created redirect file for netlify
  _redirects
Labels: production, review

#71 Updating organizer info in about page
  site/content/about/_index.md
  site/content/sponsors/_index.md
Labels: review

#80 Adding mixpanel sf event
  site/content/events/2018-10-17.md
Labels: review

#90 Credits -> Contributors
  CONTRIBUTING.md
  README.md
Labels: review

#91 Removing rsvp for past events
  site/layouts/partials/content/card/card.event.html
Labels: review

#101 Create initial open source page
  site/content/resources/open-source/_index.md
  site/content/resources/open-source/operation-code.md
Labels: review

#106 Add FOSSA status, update Waffle badge
  README.md
Labels: review

#147 Scaling the project further
  .babelrc
  .editorconfig
  .eslintrc
  .github/CODEOWNERS
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/stale.yml
  .gitignore
  .prettierrc
  .vscode/settings.json
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  _redirects
  gulpfile.babel.js
  netlify.toml
  package.json
  renovate.json
  site/archetypes/default.md
  site/content/about/brand.md
  site/content/events/2018-10-17.md
  site/layouts/index.html
  site/layouts/partials/content/children/_index.html
  site/layouts/partials/content/children/children.home.html
  site/layouts/partials/content/footer/sponsor-us.html
  site/layouts/partials/footer/who-we-are.html
  site/layouts/partials/navbar/brand.html
  src/img/homepage/homepage.jpg
  src/img/logos/logo-rectangle.png
  src/img/logos/logo-square.png
  src/img/sponsor/patreon.svg
  src/js/app.js
  src/sass/_header.scss
  webpack.dev.js
  webpack.prod.js
Labels: bug, enhancement, review

#149 fix code factor issues
  _redirects
  netlify.toml
  src/sass/_header.scss
  src/sass/_section.scss
Labels: review

#155 Make local development even easier
  .github/CONTRIBUTING.md
  .jshintrc
  README.md
  gulpfile.babel.js
  site/layouts/partials/scripts/service-worker.html
  webpack.prod.js
Labels: review
