Repository techqueria/website, pull requests merged in 2019-06, with the labels that each got.

#393 updating Slack URL
  README.md
  config.toml
  content/english/communities/chapters/austin.md
  content/english/communities/chapters/bay-area.md
  content/english/communities/chapters/chicago.md
  content/english/communities/chapters/la.md
  content/english/communities/chapters/nyc.md
  content/english/communities/slack.md
  content/espanol/communities/chapters/austin.md
  content/espanol/communities/chapters/chicago.md
  content/espanol/communities/slack.md
Labels: PR: unreviewed

#376 Added Student resource category #357
  config.toml
  content/english/resources/students/_index.md
Labels: PR: reviewed-approved

#395 add mailclark and netlify
  assets/img/banners/mailclark.png
  content/english/communities/slack.md
  content/english/donate/_index.md
  content/english/events/2017-04-06-designers-in-oakland.md
  content/english/support-us/_index.md
  content/english/support-us/supporters/mailclark.md
  content/english/support-us/supporters/netlify.md
  content/espanol/donate/_index.md
  content/espanol/events/2017-04-06-designers-in-oakland.md
  content/espanol/events/_index.md
  layouts/partials/base/footer/copyright.html
  layouts/partials/base/head/seo.html
Labels: PR: reviewed-changes-requested

#397 update team members
  content/english/team/dalia-icedo.md
  content/english/team/hector-carmona.md
  content/english/team/josue-bustos.md
  content/english/team/kevin-hernandez.md
  content/english/team/phillip-ventura.md
  content/english/team/rubi-sanchez.md
  content/espanol/team/dalia-icedo.md
  content/espanol/team/hector-carmona.md
  content/espanol/team/josue-bustos.md
  content/espanol/team/kevin-hernandez.md
  content/espanol/team/phillip-ventura.md
  content/espanol/team/rubi-sanchez.md
Labels: PR: unreviewed

#396 Feature/add meetup events
  README.md
  config.toml
  content/english/events/_index.md
  content/english/events/sub_events/_index.md
  layouts/partials/content/meetup.html
  layouts/section/sub_events/meetup.html
Labels: PR: unreviewed
