Repository techqueria/website, pull requests merged in 2020-07, with the labels that each got.

#676 Fix link for Spanish readme
  README.md
Labels: PR: partially-approved

#678 CoC changes
  content/english/about/code-of-conduct.md
Labels: PR: unreviewed

#679 fvntr: changing my name
  README.md
Labels: PR: unreviewed

#680 fvntr: updating triplebyte link
  content/english/supporters/triplebyte.md
Labels: PR: unreviewed

#684 Revert "Update dependency bulma to ^0.9.0"
  package.json
Labels: PR: unreviewed

#693 fvntr: adding sf business times article
  assets/img/news/2020-07-03-moving-diversity-beyond-a-hashtag.jpg
  content/news/2020-07-03-moving-diversity-beyond-a-hashtag.md
Labels: PR: unreviewed

#694 fvntr: adding protocol article
  assets/img/news/2020-06-08-protocol.jpg
  content/news/2020-06-08-reinventing-techs-pipeline.md
Labels: PR: reviewed-approved

#695 update job postings page
  config.toml
  content/support-us/marketing-packages.md
Labels: PR: unreviewed
