Repository techqueria/website, pull requests merged in 2020-05, with the labels that each got.

#647 fixing typos in news articles
  content/english/news/2019-03-22-sentry-open-source.md
  content/english/news/2019-04-09-latinx-online-communities.md
  content/english/news/2019-07-18-el-tecolote.md
Labels: PR: reviewed-approved

#653 Frances fixes
  content/english/support-us/partner/job-postings.md
  drafts/_index.md
  drafts/board-advisor.md
  drafts/board-chair.md
  drafts/board-member.md
  drafts/chapter-director-application.md
  drafts/diamond.md
  drafts/executive-director.md
  drafts/gold.md
  drafts/marketing-packages.md
  drafts/platinum.md
  drafts/secretary.md
  drafts/silver.md
  drafts/titanium.md
  drafts/treasurer.md
Labels: PR: unreviewed

#654 fix success page
  content/english/success-chapter-director.md
  content/english/success-member.md
  content/english/success-testimonial.md
  content/english/success.md
  content/english/success/contact.md
  content/english/testimonials/_index.md
Labels: PR: unreviewed

#655 Frances fixes
  assets/img/supporters/general-assembly.png
  config.toml
  content/english/join/_index.md
  content/english/support-us/_index.md
  content/english/support-us/chapter-director.md
  content/english/support-us/chapter-director/application.md
  content/english/support-us/chapter-director/chapter-tiers.md
  content/english/support-us/chapter-director/reimbursement-policy/_index.md
  content/english/support-us/chapter-director/reimbursement-policy/open-collective.md
  content/english/support-us/community-partner.md
  content/english/support-us/corporate-events.md
  content/english/support-us/custom-partnerships.md
  content/english/support-us/job-postings.md
  content/english/support-us/partner/_index.md
  content/english/support-us/software-sponsor.md
  content/english/support-us/speak.md
  content/english/support-us/volunteer.md
  content/english/supporters/general-assembly.md
  drafts/marketing-packages.md
  i18n/en.toml
  layouts/404.html
  layouts/partials/content/_index.html
  layouts/partials/content/child-smaller.html
  layouts/partials/content/children.html
  layouts/partials/content/cta/cta.donate.html
  layouts/partials/content/cta/cta.member.html
  layouts/partials/content/cta/cta.newsletter.html
  layouts/partials/content/cta/cta.shop.html
  layouts/partials/content/cta/cta.slack.html
  layouts/partials/content/cta/cta.sponsor.html
  layouts/partials/content/custom/supporters-showcase.html
  layouts/partials/content/hero/hero-links.html
  layouts/shortcodes/allies.html
  layouts/shortcodes/core-sponsorship-packages.html
  static/_redirects
Labels: PR: unreviewed

#657 Add Help Scout
  content/english/support-us/custom-partnerships.md
  content/english/support-us/job-postings.md
  layouts/partials/base/scripts.html
  layouts/partials/base/scripts/help-scout.html
  layouts/shortcodes/core-sponsorship-packages.html
Labels: PR: unreviewed

#658 fix twemoji
  assets/js/components/externalLinks.js
  assets/js/components/twemoji.js
  assets/js/join.js
  content/english/support-us/_index.md
  content/english/support-us/custom-partnerships.md
  layouts/_default/custom/page-support-us.html
  layouts/partials/base/scripts.html
  layouts/partials/base/scripts/twemoji.html
  layouts/partials/content/custom/partnership-call.html
  layouts/partials/content/custom/partnerships-deck.html
  layouts/shortcodes/core-sponsorship-packages.html
  layouts/shortcodes/deck.html
  package.json
  webpack.dev.js
  webpack.prod.js
Labels: PR: unreviewed, needs-more-info

#660 Publish blog post
  assets/img/news/2020-05-29.jpg
  content/english/news/2020-05-29-solidarity-for-the-black-community.md
  content/english/support-us/job-postings.md
  layouts/partials/base/scripts.html
  layouts/partials/base/scripts/netlify-identity.html
  static/admin/config.yml
  static/admin/index.html
  webpack.dev.js
  webpack.prod.js
Labels: PR: unreviewed, needs-more-info

#661 Update blog post
  content/english/news/2020-05-29-solidarity-for-the-black-community.md
  package.json
  static/admin/config.yml
Labels: PR: unreviewed
