Repository techqueria/website, pull requests merged in 2020-10, with the labels that each got.

#763 New press articles to Techqueria News
  README.md
  assets/img/news/2019-10-14-heritage-month.jpg
  assets/img/news/2020-05-09-tech-workforce.jpg
  assets/img/news/2020-06-15-black-latinx-hired.jpg
  assets/img/news/2020-07-23-latinx-tech-communities.jpg
  assets/img/news/2020-08-01-latinx-founders-funding.jpeg
  content/news/2019-10-14-heritage-month.md
  content/news/2020-05-09-tech-workforce.md
  content/news/2020-06-15-black-latinx-hired.md
  content/news/2020-07-23-latinx-tech-communities.md
  content/news/2020-08-01-latinx-founders-funding.md
Labels: PR: reviewed-approved

#772 Frances fixes
  assets/img/summit/sponsors/Thumbs.db
  assets/sass/_summit.scss
  assets/sass/_utilities.scss
  content/partner.md
  content/success/success-summit.md
  content/supporters/calendly.md
  layouts/_default/custom/summit.html
  layouts/partials/content/custom/partnership-call.html
  layouts/partials/summit/hero.html
  layouts/partials/summit/raffle-prizes.html
  layouts/partials/summit/rsvp.html
  layouts/partials/summit/schedule.html
  layouts/partials/summit/schedule/day-1.html
  layouts/partials/summit/schedule/day-2.html
  layouts/partials/summit/schedule/day-3.html
Labels: PR: unreviewed, needs-more-info

#775 update speakers
  assets/img/summit/sponsors/Thumbs.db
  data/speakers.json
Labels: PR: unreviewed

#777 fvntr: summit updates
  assets/img/summit/performers/chulita-vinyl-club.jpg
  assets/img/summit/performers/sally-limon.png
  assets/img/summit/speakers/Barbara Teyssandier.jpg
  assets/img/summit/speakers/barbara-teyssandier.jpg
  assets/img/summit/speakers/cat-martinez.jpg
  assets/img/summit/speakers/catalina-perez.jpg
  assets/img/summit/speakers/cesar-manara.jpg
  assets/img/summit/speakers/claire-miller.jpg
  assets/img/summit/speakers/julieta-dasilva.jpg
  assets/img/summit/speakers/karina-macias-sandoval.jpg
  assets/img/summit/speakers/kendra-ritterhern.jpg
  assets/img/summit/speakers/lisa-del-sol.jpg
  assets/img/summit/speakers/stephanie-rivera.jpg
  assets/img/summit/speakers/yesenia-rosales.jpg
  assets/img/summit/sponsors/adobe.png
  data/performers.json
  data/speakers.json
Labels: PR: unreviewed

#779 fvntr: adding appdynamics as sponsor
  assets/img/summit/sponsors/appdynamics.png
  data/speakers.json
  layouts/partials/summit/schedule/day-2.html
  layouts/partials/summit/sponsors.html
Labels: PR: unreviewed

#770 feat: Add description paragraph to new silver-sponsor and add Triplebyte footer
  content/supporters/northeastern.md
  layouts/partials/content/footer/_index.html
  layouts/partials/content/footer/triplebyte.html
Labels: PR: reviewed-approved
