Repository techqueria/website, pull requests merged in 2021-01, with the labels that each got.

#835 fvntr: adding 1-13 announcement
  assets/img/news/2021-01-13-response-to-capitol-attack.png
  content/news/2021-01-13-reflection-on-capitol-attack.md
Labels: PR: unreviewed

#839 Added new articles and partners
  assets/img/news/2020-05-25-grad-advice.jpg
  assets/img/news/2021-01-14-lyft-diversity.png
  assets/img/supporters/get-guru.png
  assets/img/supporters/latino-community-fund.png
  content/news/2019-08-26-twitter-threads.md
  content/news/2020-05-25-grad-advice.md
  content/news/2021-01-14-lyft-diversity.md
  content/supporters/guru.md
  content/supporters/latino-community-fund.md
Labels: PR: reviewed-approved

#834 Added new sponsor, and changed partner to past partners
  assets/img/supporters/ayden.png
  content/supporters/adyen.md
  content/supporters/keeptruckin.md
Labels: PR: partially-approved

#851 [Snyk] Security upgrade browser-sync from 2.26.13 to 2.26.14
  package.json
Labels: PR: unreviewed

#850 Moved partner to past partner, removed #meta from the join page
  content/supporters/home-depot.md
  layouts/shortcodes/allies.html
Labels: PR: partially-approved

#855 Added new partners, updated testimonial, removed resource
  README.md
  assets/img/supporters/blacks-in-technology.png
  assets/img/supporters/offensive-security.png
  content/resources/immigration/center-for-immigration-studies.md
  content/supporters/blacks-in-technology.md
  content/supporters/offensive-security.md
  content/testimonials/2019-10-09-gabriela-contreras-cisneros.md
Labels: PR: partially-approved
